import type { Article } from './types';

export const articles: Article[] = [
  {
    id: '1',
    title: 'Global Leaders Convene for Emergency Climate Summit Amidst Rising Sea Levels',
    slug: 'global-leaders-climate-summit-rising-sea-levels',
    summary: 'World leaders gather in Geneva to discuss urgent measures against climate change as new reports indicate faster-than-expected sea-level rise.',
    content: 'Full article content goes here...',
    imageId: 'article-1',
    category: 'World',
    tags: ['Climate Change', 'Politics', 'Environment'],
    author: 'Elena Petrova',
    publishedDate: '2024-07-28',
    status: 'published',
  },
  {
    id: '2',
    title: 'Tech Giant "Innovate Inc." Unveils Revolutionary Quantum Computing Chip',
    slug: 'innovate-inc-quantum-computing-chip',
    summary: 'Innovate Inc. has just announced a breakthrough in quantum computing that could reshape the entire technology landscape.',
    content: 'Full article content goes here...',
    imageId: 'article-2',
    category: 'Technology',
    tags: ['Quantum Computing', 'Innovation', 'Tech'],
    author: 'Ben Carter',
    publishedDate: '2024-07-28',
    status: 'published',
  },
  {
    id: '3',
    title: 'Market Volatility Increases as Central Bank Hints at Interest Rate Hike',
    slug: 'market-volatility-interest-rate-hike',
    summary: 'Investors are on edge after the Central Bank chairman suggested that an interest rate hike may be coming sooner than anticipated to combat inflation.',
    content: 'Full article content goes here...',
    imageId: 'article-3',
    category: 'Business',
    tags: ['Economy', 'Finance', 'Markets'],
    author: 'Sophia Chen',
    publishedDate: '2024-07-28',
    status: 'published',
  },
  {
    id: '4',
    title: 'Historic Peace Treaty Signed Between Warring Nations of Arcania and Krystallos',
    slug: 'peace-treaty-arcania-krystallos',
    summary: 'After decades of conflict, the neighboring countries of Arcania and Krystallos have signed a landmark peace agreement.',
    content: 'Full article content goes here...',
    imageId: 'article-4',
    category: 'Politics',
    tags: ['Peace', 'International Relations'],
    author: 'Marcus Thorne',
    publishedDate: '2024-07-27',
    status: 'published',
  },
  {
    id: '5',
    title: 'Breakthrough in Alzheimer\'s Research: New Drug Shows Promise in Early Trials',
    slug: 'alzheimers-research-new-drug-promise',
    summary: 'A new experimental drug has shown significant potential in slowing the progression of Alzheimer\'s disease in its early stages.',
    content: 'Full article content goes here...',
    imageId: 'article-5',
    category: 'Health',
    tags: ['Medicine', 'Science', 'Research'],
    author: 'Dr. Evelyn Reed',
    publishedDate: '2024-07-27',
    status: 'published',
  },
  {
    id: '6',
    title: '"Starfield Odyssey" Sweeps the Box Office with Record-Breaking Opening Weekend',
    slug: 'starfield-odyssey-box-office-record',
    summary: 'The latest sci-fi epic, "Starfield Odyssey," has shattered box office records, grossing over $200 million domestically in its opening weekend.',
    content: 'Full article content goes here...',
    imageId: 'article-6',
    category: 'Entertainment',
    tags: ['Movies', 'Box Office', 'Sci-Fi'],
    author: 'Liam Goldberg',
    publishedDate: '2024-07-26',
    status: 'published',
  },
  {
    id: '7',
    title: 'The Future of Urban Transportation: Are Flying Taxis Finally Here?',
    slug: 'future-urban-transportation-flying-taxis',
    summary: 'Several companies are now testing autonomous flying taxi services in major cities, promising a revolution in how we commute.',
    content: 'Full article content goes here...',
    imageId: 'article-7',
    category: 'Technology',
    tags: ['Transportation', 'Innovation', 'Smart Cities'],
    author: 'Jenna Ortiz',
    publishedDate: '2024-07-25',
    status: 'published',
  },
    {
    id: '8',
    title: 'National Parks Report Unprecedented Visitor Numbers Post-Pandemic',
    slug: 'national-parks-visitor-numbers',
    summary: 'A surge in domestic travel has led to record-breaking visitor numbers at national parks, raising concerns about conservation and infrastructure.',
    content: 'Full article content goes here...',
    imageId: 'article-8',
    category: 'Lifestyle',
    tags: ['Travel', 'Nature', 'Environment'],
    author: 'David Chen',
    publishedDate: '2024-07-24',
    status: 'published',
  },
  {
    id: '9',
    title: 'Political Tensions Escalate in the South China Sea',
    slug: 'political-tensions-south-china-sea',
    summary: 'Recent naval maneuvers have heightened tensions between major world powers in the strategically vital South China Sea region.',
    content: 'Full article content goes here...',
    imageId: 'article-9',
    category: 'World',
    tags: ['Politics', 'Military', 'International Relations'],
    author: 'Aisha Khan',
    publishedDate: '2024-07-23',
    status: 'published',
  },
  {
    id: '10',
    title: 'Education Reform Bill Passes, Promising Overhaul of National Curriculum',
    slug: 'education-reform-bill-passes',
    summary: 'A controversial education reform bill has narrowly passed, setting the stage for the biggest curriculum changes in a generation.',
    content: 'Full article content goes here...',
    imageId: 'article-10',
    category: 'National',
    tags: ['Education', 'Politics', 'Law'],
    author: 'Samuel Jones',
    publishedDate: '2024-07-22',
    status: 'published',
  },
   {
    id: '11',
    title: 'How AI is Revolutionizing Sports Analytics and Strategy',
    slug: 'ai-sports-analytics-strategy',
    summary: 'Professional sports teams are increasingly leveraging artificial intelligence to analyze player performance and develop winning game strategies.',
    content: 'Full article content goes here...',
    imageId: 'article-11',
    category: 'Sports',
    tags: ['AI', 'Technology', 'Analytics'],
    author: 'Chloe Kim',
    publishedDate: '2024-07-21',
    status: 'published',
  },
];
